### PR TITLE
Add new section for influencers

### PR DESCRIPTION
**Pull request by firstlutfi**
Add a new section for influencers. The parameters (what can I think of) are the following:
- At least 5 years of experience in the QA industry, preferably the one who has a lead/manager title
- Regularly posted something (related to QA) in their Linkedin feed at least once a week

### CODE REVIEW

**Comment by FachrulCH** [comment]
tambahin donk isi orang nya @firstlutfi , takut dikira monopoli isinya gw doank 😅

**Comment by FachrulCH** [comment]
dan yang penting bikin parameter orang kek mana yang bisa masuk kategori ini, linkedin sih udah paling cocok ketimbang personal IG, beberapa orang juga gw liat sering share materi bagus soal QA

**Comment by FachrulCH** [comment]
sebagai inspirasi mungkin bisa cekidot format kek gini:

- https://techbeacon.com/app-dev-testing/28-qa-professionals-you-should-follow-twitter
- https://www.practitest.com/qa-learningcenter/resources/top-20-twitter-influencers/

**Comment by firstlutfi** [comment]
updated

**Pull request merged**
